//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int DID { get; set; }
        public string MCC { get; set; }
        public string FULLname { get; set; }
        public string Expert { get; set; }
        public string Proprietary { get; set; }
        public string Floship { get; set; }
        public string Email { get; set; }
        public string DSex { get; set; }
        public string Mobile { get; set; }
        public string Workcity { get; set; }
        public string Workname { get; set; }
        public string Workphone { get; set; }
        public string Workaddress { get; set; }
    }
}
