//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        public int RID { get; set; }
        public Nullable<int> VID { get; set; }
        public string MCC { get; set; }
        public string Rtext { get; set; }
    }
}
