//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int VID { get; set; }
        public string MCC { get; set; }
        public string UNcode { get; set; }
        public string Cate { get; set; }
        public string Qtitle { get; set; }
        public string Qtext { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Vage { get; set; }
        public Nullable<int> Vheight { get; set; }
        public Nullable<int> Vweight { get; set; }
        public string Qother { get; set; }
        public string Qspecial { get; set; }
        public string Qdrug { get; set; }
        public string Qamal { get; set; }
        public string Qfamily { get; set; }
        public string Qothercase { get; set; }
        public string Supphone { get; set; }
        public string Supmail { get; set; }
    }
}
